# Zeilen filtern mit `filter`

## TL;DR{.unlisted .unnumbered}

- Mit dem `filter` Befehl können wir eine Untermenge der gesamten Zeilen eines Datensatzes auswählen.
- Alphanumersiche nominalskalierte Spalten können wir mit dem `==` Operator auf einen bestimmten Wert filtern.

```{r, echo=FALSE}
library(knitr)
hook_output <- knit_hooks$get("output")
knit_hooks$set(output = function(x, options) {
  lines <- options$output.lines
  if (is.null(lines)) {
    return(hook_output(x, options))  # pass to default hook
  }
  x <- unlist(strsplit(x, "\n"))
  more <- "..."
  if (length(lines)==1) {        # first n lines
    if (length(x) > lines) {
      # truncate the output, but add ....
      x <- c(head(x, lines), more)
    }
  } else {
    x <- c(more, x[lines], more)
  }
  # paste these lines together
  x <- paste(c(x, ""), collapse = "\n")
  hook_output(x, options)
})
``` 


```{r, include=FALSE}
library(tidyverse)
```

```{r, include=FALSE}
pokemon <- read_csv("datasets/pokemon.csv")
```

## Filtern von alphanumerischen Werten (Zeichenketten)

### Filtern auf Gleichheit

```{r}
pokemon %>%
  select(name)
```

